export const SEARCH = "SEARCH";

export const SEARCH_CALL_REQUEST = "SEARCH_CALL_REQUEST";
export const SEARCH_CALL_SUCCESS = "SEARCH_CALL_SUCCESS";
export const SEARCH_CALL_FAIL = "SEARCH_CALL_FAIL";
